TEF1 <- c("CATCGAGAAGTTCGAGAAGG","AACTTGCAGGCAATGTGG")

RPB2 <- c(  "GATGATAGAGATCACTTTGG","GATGATAGAGATCACTTCGG","GATGATAGAGATCACTATGG","GATGATAGAGATCACTATCG",
                          "GATGATAGTGATCACTTTGG","GATGATAGTGATCACTTCGG","GATGATAGTGATCACTATGG","GATGATAGTGATCACTATCG",
                          "GATGATCGAGATCACTTTGG","GATGATCGAGATCACTTCGG","GATGATCGAGATCACTATGG","GATGATCGAGATCACTATCG",
                          "GATGATCGTGATCACTTTGG","GATGATCGTGATCACTTCGG","GATGATCGTGATCACTATGG","GATGATCGTGATCACTATCG",
                          "GATGACAGAGATCACTTTGG","GATGACAGAGATCACTTCGG","GATGACAGAGATCACTATGG","GATGACAGAGATCACTATCG",
                          "GATGACAGTGATCACTTTGG","GATGACAGTGATCACTTCGG","GATGACAGTGATCACTATGG","GATGACAGTGATCACTATCG",
                          "GATGACCGAGATCACTTTGG","GATGACCGAGATCACTTCGG","GATGACCGAGATCACTATGG","GATGACCGAGATCACTATCG",
                          "GATGACCGTGATCACTTTGG","GATGACCGTGATCACTTCGG","GATGACCGTGATCACTATGG","GATGACCGTGATCACTATCG",
                          "GACGATAGAGATCACTTTGG","GACGATAGAGATCACTTCGG","GACGATAGAGATCACTATGG","GACGATAGAGATCACTATCG",
                          "GACGATAGTGATCACTTTGG","GACGATAGTGATCACTTCGG","GACGATAGTGATCACTATGG","GACGATAGTGATCACTATCG",
                          "GACGATCGAGATCACTTTGG","GACGATCGAGATCACTTCGG","GACGATCGAGATCACTATGG","GACGATCGAGATCACTATCG",
                          "GACGATCGTGATCACTTTGG","GACGATCGTGATCACTTCGG","GACGATCGTGATCACTATGG","GACGATCGTGATCACTATCG",
                          "GACGACAGAGATCACTTTGG","GACGACAGAGATCACTTCGG","GACGACAGAGATCACTATGG","GACGACAGAGATCACTATCG",
                          "GACGACAGTGATCACTTTGG","GACGACAGTGATCACTTCGG","GACGACAGTGATCACTATGG","GACGACAGTGATCACTATCG",
                          "GACGACCGAGATCACTTTGG","GACGACCGAGATCACTTCGG","GACGACCGAGATCACTATGG","GACGACCGAGATCACTATCG",
                          "GACGACCGTGATCACTTTGG","GACGACCGTGATCACTTCGG","GACGACCGTGATCACTATGG","GACGACCGTGATCACTATCG",
                          "CCCATAGCTTGTTTACCCAT","CCCATAGCTTGTTTGCCCAT","CCCATAGCTTGCTTACCCAT","CCCATAGCTTGCTTGCCCAT",
                          "CCCATGGCTTGTTTACCCAT","CCCATGGCTTGTTTGCCCAT","CCCATGGCTTGCTTACCCAT","CCCATGGCTTGCTTGCCCAT",
                          "ATGGGTAAACAAGCCATGGG","GACGATCGCGACCACTTTGG"
)
ITS <-  c("GGAAGTAAAAGTCGTAACAAGG","TCCTCCGCTTATTGATATGC")

LNS2 <- c(
  "GTCCAGTCTCGGCCAATCATGTTGAGCACATGGCC",
  "GACGGCGGTCCTTTCTATGCCGGGTTTGGCAACCG",
  "AACGGCGGTCCTTTCTATGCCGGCTTTGGCAACCG",
  "GTCCAGTCTCGGCCAATCATGTTGAGCACATGACC",
  "GTCCAGTCTCGACCAATCATGTTTAGCACATGACC",
  "GACGGTGGTCCTTTCTATGCCGGGTTTGGCAACCG",
  "GACGGCGGACCTTTCTATGCCGGTTTTGGCAACCG",
  "GTCCAGTCTCGGCCAATCATATTCAGCACATGACC",
  "GTCCAGTCTCGGCCGATCATGTTGAGCACATGGCC",
  "GACGGCGGTCCTTTCTATGCCGGTTTCGGCAATCG",
  "GACACCGTCCCCTTCTATGCCGGTTTTGGCAACCG",
  "GTCCAGTCTCGGCCAATCATGTTCAGCACATGGCC",
  "GTCCAGTCGCGGCCAATCATGTTGAGCACATGGCC",
  "GTCCAGTCTCGGCCAATCATGTTCAACACATGGCC",
  "GTCCAGTCTCGGCCAATCATATTCAGCACATGCCC",
  "GACGGCGGTCCTTTCTATGCCGGATTTGGCAACCG",
  "GTCCAGTCTCGGCCAATCATATTCAGCACATGGCC",
  "GACGGTACTCCTTTCTATGCCGGTTTTGGCAACCG",
  "GACGGTGGTCCTTTCTATGCCGGTTTTGGCAACCG",
  "GATGGCGGCCCTTTCTATGCTGGATTCGGCAACCG",
  "GACGGCGGTCCCTTCTATGCCGGGTTCGGCAACCG",
  "GTCCAGTCTCGGCCAATCATGTTGAGTACATGACC",
  "GACGGTGGTCCTTTCTATGCCGGATTTGGCAACCG",
  "GACGGTGGTCCTTTCTATGCCGGCTTTGGCAACCG",
  "GACGGTGGTCCTTTCTACGCCGGGTTTGGCAACCG",
  "GACGGCGGTCCCTTCTACGCCGGGTTTGGCAACCG",
  "CGGTTGCCAAAGCCGGCGTAGAATGGACCGCCGTT",
  "GGTCATGTGCTCAACATGATTGGCCGAGACTGGAC",
  "GGCCATGTGCTCAACATGATTGGCCGCGACTGGAC",
  "CGGTTGCCAAACCCGGCATAGAAAGGACCGCCGTC",
  "CGGTTGCCAAAGCCGGCATAGAATGGACCTCCGTC",
  "GGCCATGTGCTCAACATGATTGGCCGAGACTGGAC",
  "CGGTTACCAAAACCGGCGTAGAAAGGACCGCCGTC",
  "CGGTTGCCAAAGCCGGCGTAGAAAGGACCGCCGTT",
  "GGCCATGTGCTCAACATGATCGGCCGAGACTGGAC",
  "GGCCACGTGCTCAACATGATCGGCCGAGACTGGAC",
  "CGGTTGCCAAAGCCGGCATAGAATGGACCACCGTC",
  "CGGTTGCCAAAGCCGGCATAGAAAGGACCGCCGTT",
  "CGGTTGCCAAATCCGGCATAGAAAGGAGTACCGTC",
  "CGGTTGCCAAAACCGGCATAGAAAGGACCACCGTC",
  "CGGTTGCCAAAGCCGGCATAGAAAGGACCACCGTC",
  "GGTCATGTGCTGAACATGATTGGTCGAGACTGGAC",
  "GGCCATGTGCTGAACATGATCGGTCGAGACTGGAC",
  "GGCCATGTGCTGAATATGATTGGCCGAGACTGGAC",
  "GGTCATGTGCTCAACTATATTGGCCGAGACTGGAC",
  "CGGTTGCCAAAGCCGGCATAGAAAGGACCGCCATC",
  "CGGTTGCCGAAACCGGCATAGAAAGGACCACCGTC",
  "CGGTTGCCAAAACCGGCATAGAAAGGAGTGCCGTC",
  "GGCCATGTGCTGAACATGATTGGCCGAGATTGGAC",
  "CGGTTACCAAACCCGGCATAGAAAGGACCGCCGTC",
  "CGGTTGCCAAACCCGGCGTAGAATGGACCGCCGTT",
  "CGGTTGCCAAAACCGGCATAGAAAGGAGTACCGTC",
  "CGGTTGCCAAAGCCGGCATAGAAAGGACCGCCGTC",
  "CGGTTGCCAAACCCGGCATAGAAAGGACCGCCGTT",
  "GGCCATGTGCTGAACATGATTGGCCGAGACTGGAC"
)

ACT <- c(
  "TGGGTCAGAAGGACTCCTA",
  "CGAAACCGGCCTTGCACAT",
  "TGGGCCAGAAGGACTCTTA",
  "TGGGCCAGAAGGACTCCTA",
  "CGAAACCGGCTTTGCACAT",
  "TGGGTCAGAAGGACTCTTA",
  "ATGTGCAAGGCCGGTTTCG",
  "TAGGAGTCCTTCTGACCCA",
  "ATGTGCAAGGCCGGTTTTG",
  "TAGGAGTCCTTCTGGCCCA",
  "TAAGAGTCCTTCTGGCCCA"
)

TUB2 <- c(
  "CCACCGCCGAGGGAGTGGGTGAT",
  "CCACCACCCAGCGAGTGCGTAAT",
  "TCCCTCGTCTGCACTTCTTCATG",
  "TCCCTCGCCTGCACTTCTTCATG",
  "CCACCACCGAGGGAGTGGGTGAT",
  "TCCCTCGTCTCCACTTCTTCATG",
  "CCACCACCCAGGGAGTGTGTAAT",
  "TTCCTCGTCTGCACTTCTTCATG",
  "TCCCCCGTCTCCACTTCTTCATG",
  "CCACCGCCAAGGGAGTGTGTAAT",
  "CCACCACCAAGGGAGTGGGTGAT",
  "TCCCTCGTCTTCACTTCTTCATG",
  "CCACCACCCAGGGAGTGCGTAAT",
  "TCCCGCGTCTCCACTTCTTTATG",
  "CCACCACCCAGGGAGTGGGTAAT",
  "TCCCTCGTCTGCATTTCTTCATG",
  "CCACCACCGAGAGAGTGGGTGAT",
  "TCCCTCGTCTCCATTTCTTCATG",
  "TCCCCCGTCTCCATTTCTTCATG",
  "CCGCCACCCAGCGAGTGTGTAAT",
  "CCACCACCCAGAGAGTGTGTAAT",
  "CCGCCACCCAGCGAGTGCGTAAT",
  "CCACCACCCAGGGAGTGGGTGAT",
  "CCACCACCGAGCGAGTGGGTGAT",
  "CCGCCACCGAGGGAGTGGGTGAT",
  "TCCCCCGTCTGCACTTCTTCATG",
  "TCCCTCGTCTGCACTTTTTCATG",
  "CCACCACCCAGCGAGTGTGTAAT",
  "CCACCGCCAAGGGAGTGGGTGAT",
  "CATAAAGAAGTGGAGACGGGGGA",
  "CATGAAGAAGTGCAGACGAGGGA",
  "CATGAAGAAGTGGAGACGGGGGA",
  "ATTACACACTCCCTGGGTGGTGG",
  "ATTACCCACTCGCTGGGTGGTGG",
  "CATGAAGAAGTGAAGACGAGGGA",
  "CATGAAGAAATGGAGACGGGGGA",
  "ATTACCCACTCCCTGGGTGGTGG",
  "ATCACCCACTCCCTCGGTGGTGG",
  "ATCACACACTCCCTTGGTGGTGG",
  "CATGAAGAAATGCAGACGAGGGA",
  "ATTACACACTCCTTGGGTGGTGG",
  "ATTACTCACTCTCTTGGTGGTGG",
  "ATCACCCACTCCCTGGGTGGTGG",
  "CATGAAGAAGTGGAGACGAGGGA",
  "ATTACCCACTCGCTGGGTGGCGG",
  "ATCACCCACTCCCTCGGCGGTGG",
  "ATCACCCACTCTCTCGGTGGTGG",
  "ATCACCCACTCCCTTGGTGGTGG",
  "ATCACGCACTCCCTGGGTGGTGG",
  "CATGAAGAAGTGTAGACGAGGGA",
  "ATCACTCACTCCCTGGGTGGTGG",
  "ATCACCCACTCCCTCGGTGGCGG",
  "ATTACACACTCCCTGGGCGGTGG",
  "CATAAAGAAGTGCAGACGAGGGA",
  "CATGAAAAAGTGCAGACGAGGGA",
  "ATCACCCACTCCCTCGGCGGCGG",
  "ATTACGCACTCGCTGGGTGGTGG",
  "ATCACCCACTCGCTCGGTGGTGG",
  "ATTACGCACTCCCTGGGTGGTGG"
)

TEF3 <- c(
  "CTTCATCTTCCAACCACCAGA",
  "CTTGAGGGTGTCAAGACCAAG",
  "CTTCATCTTCCAACCACCGGA",
  "CTCGAGGGTGTCAAGACCAAG",
  "CTGGAGGGTGTCAAGACCAAG",
  "CTTGAGGGCGTCAAGACCAAG",
  "CTTGGTCTTGACACCCTCGAG",
  "TCCGGTGGTTGGAAGATGAAG",
  "TCTGGTGGTTGGAAGATGAAG",
  "CTTGGTCTTGACACCCTCAAG",
  "CTTGGTCTTGACACCTTCGAG",
  "CTTGGTTTTGACACCCTCAAG",
  "CTTGGTCTTGACACCTTCAAG"
)

PGK <- c(
  "ATCTTGTCAGAGACCTTGGCGCCGC",
  "GTCGGTGCCATTCCCACCATCAAGC",
  "GTCGGCGCCATCCCGACCATCAAGC",
  "GTTGGCGCCATCCCCACCATCAAGC",
  "ATCTTGTCAGAGACCTTGGCACCGC",
  "GTCGGTGCCATCCCTACCATCAAGC",
  "ATCTTGTCAGAGACCTTGGCACCAC",
  "ATCTTGTCAGAGACCTTGGCACCTC",
  "ATCTTGTCAGAGACCTTAGCACCGC",
  "GTCGGCGCCATCCCCACCATCAAGC",
  "ATCTTGTCAGAGACCTTGGCGCCAC",
  "GTCGGCGCCATCCCTACCATCAAGC",
  "GTCGGTGCCATCCCCACCATCAAGC",
  "GTTGGCGCCATCCCTACCATCAAGC",
  "GCCGGTGCCATCCCCACCATCAAGC",
  "GTCGGTGCTATCCCTACCATCAAGC",
  "GCTTGATGGTCGGGATGGCGCCGAC",
  "GCGGCGCCAAGGTCTCTGACAAGAT",
  "GTGGTGCCAAGGTCTCTGACAAGAT",
  "GCTTGATGGTGGGAATGGCACCGAC",
  "GCTTGATGGTGGGGATGGCACCGAC",
  "ATTTGATGGTTGGGATAGCGCCAAC",
  "GCGGTGCCAAGGTCTCTGACAAGAT",
  "GCGGCGCCAAGGTCTCCGACAAGAT",
  "GCTTGATGGTAGGGATGGCGCCAAC",
  "GCTTGATGGTGGGGACGGCACCGAC",
  "GTGGTGCTAAGGTCTCTGACAAGAT",
  "GCTTGATGGTAGGGATGGCGCCGAC",
  "GCTTGATGGTAGGAATAGCACCGAC",
  "GCGGGGCCAAGGTCTCTGACAAGAT",
  "GTGGTGCCAAGATCTCTGACAAGAT",
  "GCTTGATGGTAGGGACGGCACCGAC",
  "GCTTGATGGTGGGGATGGCGCCGAC",
  "GCTTGATGGTAGGGATGGCACCGAC",
  "GCTTGATGGTGGGGATGGCACCGGC",
  "GCTTGATGGTGGGAATGGCGCCGAC"
)

TOP1 <- c(
  "TAGCCGATGCTGCGATTAGCCAA",
  "ACGCGGAGGACTGGGAATTCTAG",
  "ACGCTGAAGACTGGGAATTCTAA",
  "ACGCGGAAGACTGGGAATTCTAG",
  "GAGTTGATGCTGCGATTAGCCAA",
  "GAGTCGATGCTGCGATTAGCCAA",
  "GAATTGATGCTACGATTAGCTAG",
  "AAGTCGATGCTGCGATTAGCCAA",
  "GAATTGATGCGGCGATTAGCCAG",
  "GAATTGATGCCACGATTAGCCAG",
  "GAATTGATGCTGCGATTAGCCAG",
  "ACGCAGAAGACTGGGAATTCTAA",
  "GATTCGATGCCCCGGTTAGCCAG",
  "GAATTGATGCGGCGATTAGCTAA",
  "GAGTTATGCCTGCGATTAGCCAA",
  "GAGTCAATGCTGCGATTAGCCAA",
  "GAGTCGATGCTGTTATTAGCCAA",
  "ACGCTGAAGACTGGGAGTTCTAG",
  "ACGCCGAAGACTGGGAGTTCTAG",
  "CTAGAATTCCCAGTCTTCAGCGT",
  "TTGGCTAATCGCAGCATCGACTC",
  "CTGGCTAATCGCAGCATCAATCC",
  "CTAGAATTCCCAGTCTTCTGCGT",
  "CTAGAATTCCCAGTCCTCCGCGT",
  "TTAAAATTCCCAGTCCTCTGCGT",
  "TTAGAATTCCCAGTCTTCCGCGT",
  "TTAAAATTCCCAGTCATCCGCGT",
  "TTAAAATTCCCAGTCTTCAGCAT",
  "CTGGCTAACCGTGGCATCAACTC",
  "TTAAAATTCCCAGTCTTCTGCAT",
  "CTAGAATTCCCAGTCTTCCGCGT",
  "CTAGCTAACCGTGGCATCAACTC",
  "TTAGAATTCCCAGTCTTCTGCGT",
  "TTAGAATTCCCAGTCGTCTGCGT",
  "CTAGAACTCCCAGTCCTCCGCGT",
  "CTAGAACTCCCAGTCTTCGGCGT",
  "TTGGCTAATAGCAGCATCGATTC",
  "TTAGAACTCCCAGTCGTCTGCGT",
  "AGTTGATGCCTGCGATTAGCCAA",
  "TTGGCTAATCGCAGGCATCAACT",
  "ACGCAGACGACTGGGAATTCTAA"
)

TEF1_F <- c("CATCGAGAAGTTCGAGAAGG")

TEF1_R <- c("AACTTGCAGGCAATGTGG")

ITS_F <- c("GGAAGTAAAAGTCGTAACAAGG")

ITS_R <- c("TCCTCCGCTTATTGATATGC")

RPB2_F <- c("GATGATAGAGATCACTTTGG","GATGATAGAGATCACTTCGG","GATGATAGAGATCACTATGG","GATGATAGAGATCACTATCG",
            "GATGATAGTGATCACTTTGG","GATGATAGTGATCACTTCGG","GATGATAGTGATCACTATGG","GATGATAGTGATCACTATCG",
            "GATGATCGAGATCACTTTGG","GATGATCGAGATCACTTCGG","GATGATCGAGATCACTATGG","GATGATCGAGATCACTATCG",
            "GATGATCGTGATCACTTTGG","GATGATCGTGATCACTTCGG","GATGATCGTGATCACTATGG","GATGATCGTGATCACTATCG",
            "GATGACAGAGATCACTTTGG","GATGACAGAGATCACTTCGG","GATGACAGAGATCACTATGG","GATGACAGAGATCACTATCG",
            "GATGACAGTGATCACTTTGG","GATGACAGTGATCACTTCGG","GATGACAGTGATCACTATGG","GATGACAGTGATCACTATCG",
            "GATGACCGAGATCACTTTGG","GATGACCGAGATCACTTCGG","GATGACCGAGATCACTATGG","GATGACCGAGATCACTATCG",
            "GATGACCGTGATCACTTTGG","GATGACCGTGATCACTTCGG","GATGACCGTGATCACTATGG","GATGACCGTGATCACTATCG",
            "GACGATAGAGATCACTTTGG","GACGATAGAGATCACTTCGG","GACGATAGAGATCACTATGG","GACGATAGAGATCACTATCG",
            "GACGATAGTGATCACTTTGG","GACGATAGTGATCACTTCGG","GACGATAGTGATCACTATGG","GACGATAGTGATCACTATCG",
            "GACGATCGAGATCACTTTGG","GACGATCGAGATCACTTCGG","GACGATCGAGATCACTATGG","GACGATCGAGATCACTATCG",
            "GACGATCGTGATCACTTTGG","GACGATCGTGATCACTTCGG","GACGATCGTGATCACTATGG","GACGATCGTGATCACTATCG",
            "GACGACAGAGATCACTTTGG","GACGACAGAGATCACTTCGG","GACGACAGAGATCACTATGG","GACGACAGAGATCACTATCG",
            "GACGACAGTGATCACTTTGG","GACGACAGTGATCACTTCGG","GACGACAGTGATCACTATGG","GACGACAGTGATCACTATCG",
            "GACGACCGAGATCACTTTGG","GACGACCGAGATCACTTCGG","GACGACCGAGATCACTATGG","GACGACCGAGATCACTATCG",
            "GACGACCGTGATCACTTTGG","GACGACCGTGATCACTTCGG","GACGACCGTGATCACTATGG","GACGACCGTGATCACTATCG",
            "GACGATCGCGACCACTTTGG"
)

RPB2_R <- c("CCCATAGCTTGTTTACCCAT","CCCATAGCTTGTTTGCCCAT","CCCATAGCTTGCTTACCCAT","CCCATAGCTTGCTTGCCCAT",
            "CCCATGGCTTGTTTACCCAT","CCCATGGCTTGTTTGCCCAT","CCCATGGCTTGCTTACCCAT","CCCATGGCTTGCTTGCCCAT",
            "ATGGGTAAACAAGCCATGGG"
)

LNS2_F <- c("GTCCAGTCTCGGCCAATCATGTTGAGCACATGGCC", "GACGGCGGTCCTTTCTATGCCGGGTTTGGCAACCG", "AACGGCGGTCCTTTCTATGCCGGCTTTGGCAACCG",
            "GTCCAGTCTCGGCCAATCATGTTGAGCACATGACC", "GTCCAGTCTCGACCAATCATGTTTAGCACATGACC", "GACGGTGGTCCTTTCTATGCCGGGTTTGGCAACCG",
            "GACGGCGGACCTTTCTATGCCGGTTTTGGCAACCG", "GTCCAGTCTCGGCCAATCATATTCAGCACATGACC", "GTCCAGTCTCGGCCGATCATGTTGAGCACATGGCC",
            "GACGGCGGTCCTTTCTATGCCGGTTTCGGCAATCG", "GACACCGTCCCCTTCTATGCCGGTTTTGGCAACCG", "GTCCAGTCTCGGCCAATCATGTTCAGCACATGGCC",
            "GTCCAGTCGCGGCCAATCATGTTGAGCACATGGCC", "GTCCAGTCTCGGCCAATCATGTTCAACACATGGCC", "GTCCAGTCTCGGCCAATCATATTCAGCACATGCCC",
            "GACGGCGGTCCTTTCTATGCCGGATTTGGCAACCG", "GTCCAGTCTCGGCCAATCATATTCAGCACATGGCC", "GACGGTACTCCTTTCTATGCCGGTTTTGGCAACCG",
            "GACGGTGGTCCTTTCTATGCCGGTTTTGGCAACCG", "GATGGCGGCCCTTTCTATGCTGGATTCGGCAACCG", "GACGGCGGTCCCTTCTATGCCGGGTTCGGCAACCG",
            "GTCCAGTCTCGGCCAATCATGTTGAGTACATGACC", "GACGGTGGTCCTTTCTATGCCGGATTTGGCAACCG", "GACGGTGGTCCTTTCTATGCCGGCTTTGGCAACCG",
            "GACGGTGGTCCTTTCTACGCCGGGTTTGGCAACCG", "GACGGCGGTCCCTTCTACGCCGGGTTTGGCAACCG", "GACGGCGGTCCTTTCTATGCCGGTTTTGGCAACCG",
            "GACGGTGGTCCTTTCTATGCCGGCTTTGGCAACCG"
)

LNS2_R <- c("GGCCATGTGCTCAACATGATTGGCCGAGACTGGAC", "CGGTTGCCAAACCCGGCATAGAAAGGACCGCCGTC", "CGGTTGCCAAAGCCGGCATAGAATGGACCGCCGTT",
            "GGTCATGTGCTCAACATGATTGGCCGAGACTGGAC", "GGTCATGTGCTAAACATGATTGGTGGAGACTGGAC", "CGGTTGCCAAACCCGGCATAGAAAGGACCACCGTC",
            "CGGTTGCCAAAACCGGCATAGAAAGGTCCGCCGTC", "GGTCATGTGCTGAATATGATTGGCCGAGACTGGAC", "GGCCATGTGCTCAACATGATCGGCCGAGACTGGAC",
            "CGATTGCCGAAACCGGCATAGAAAGGACCGCCGTC", "CGGTTGCCAAAACCGGCATAGAAGGGGACGGTGTC", "GGCCATGTGCTGAACATGATTGGCCGAGACTGGAC",
            "GGCCATGTGCTCAACATGATTGGCGCGACTGGAC", "GGCCATGTGTTGAACATGATTGGCCGAGACTGGAC", "GGGCATGTGCTGAATATGATTGGCCGAGACTGGAC",
            "CGGTTGCCAAATCCGGCATAGAAAGGACCGCCGTC", "GGCCATGTGCTGAATATGATTGGCCGAGACTGGAC", "CGGTTGCCAAAACCGGCATAGAAAGGAGTACCGTC",
            "CGGTTGCCAAAACCGGCATAGAAAGGACCACCGTC", "CGGTTGCCGAATCCAGCATAGAAAGGCCGCCATC", "CGGTTGCCGAACCCGGCATAGAAAGGACCGCCGTC",
            "GGTCATGTACTCAACATGATTGGCCGAGACTGGAC", "CGGTTGCCAAATCCGGCATAGAAAGGACCACCGTC", "CGGTTGCCAAAGCCGGCATAGAAAGGACCACCGTC",
            "CGGTTGCCAAACCCGGCGTAGAAAGGACCACCGTC", "CGGTTGCCGAACCCGGCGTAGAAGGACCGCCGTC", "CGGTTGCCAAAACCGGCATAGAAAGGACCGCCGTC",
            "CGGTTGCCAAAGCCGGCATAGAAAGGACCACCGTC"
)

ACT_F <- c("TGGGTCAGAAGGACTCCTA", "CGAAACCGGCCTTGCACAT", "TGGGCCAGAAGGACTCTTA", "TGGGCCAGAAGGACTCCTA",
           "CGAAACCGGCTTTGCACAT", "TGGGTCAGAAGGACTCTTA", "ATGTGCAAGGCCGGTTTTG"
)

ACT_R <- c("TAGGAGTCCTTCTGACCCA", "ATGTGCAAGGCCGGTTTCG", "TAAGAGTCCTTCTGGCCCA", "TAGGAGTCCTTCTGGCCCA"
)

TUB2_F <- c("CCACCGCCGAGGGAGTGGGTGAT", "CCACCACCCAGCGAGTGCGTAAT", "TCCCTCGTCTGCACTTCTTCATG", "TCCCTCGCCTGCACTTCTTCATG",
            "CCACCACCGAGGGAGTGGGTGAT", "TCCCTCGTCTCCACTTCTTCATG", "CCACCACCCAGGGAGTGTGTAAT", "TTCCTCGTCTGCACTTCTTCATG",
            "TCCCCCGTCTCCACTTCTTCATG", "CCACCGCCAAGGGAGTGTGTAAT", "CCACCACCAAGGGAGTGGGTGAT", "TCCCTCGTCTTCACTTCTTCATG",
            "CCACCACCCAGGGAGTGCGTAAT", "TCCCGCGTCTCCACTTCTTTATG", "CCACCACCCAGGGAGTGGGTAAT", "TCCCTCGTCTGCATTTCTTCATG",
            "CCACCACCGAGAGAGTGGGTGAT", "TCCCTCGTCTCCATTTCTTCATG", "TCCCCCGTCTCCATTTCTTCATG", "CCGCCACCCAGCGAGTGTGTAAT",
            "CCACCACCCAGAGAGTGTGTAAT", "CCGCCACCCAGCGAGTGCGTAAT", "CCACCACCCAGGGAGTGGGTGAT", "CCACCACCGAGCGAGTGGGTGAT",
            "CCGCCACCGAGGGAGTGGGTGAT", "TCCCCCGTCTGCACTTCTTCATG", "TCCCTCGTCTGCACTTTTTCATG", "CCACCACCCAGCGAGTGTGTAAT",
            "CCACCGCCAAGGGAGTGGGTGAT", "CATAAAGAAGTGGAGACGGGGGA"
)

TUB2_R <- c("ATCACCCACTCCCTCGGCGGTGG", "ATTACGCACTCGCTGGGTGGTGG", "CATGAAGAAGTGCAGACGAGGGA", "CATGAAGAAGTGCAGGCGAGGGA",
            "ATCACCCACTCCCTCGGTGGTGG", "CATGAAGAAGTGGAGACGAGGGA", "ATTACACACTCCCTGGGTGGTGG", "CATGAAGAAGTGCAGACGAAGAA",
            "CATGAAGAAATGGAGACGGGGGA", "ATTACACACTCCTTGGGTGGTGG", "ATCACCCACTCCTTGGTGGTGG", "CATGAAGAAGTGAAGACGAGGGA",
            "ATTACGCACTCCCTGGGTGGTGG", "CATAAAGAAGTGGAGACGCGGGA", "ATTACCCACTCCCTGGGTGGTGG", "CATGAAGAAATGCAGACGAGGGA",
            "ATCACCCACTCTCTCGGTGGTGG", "CATGAAGAAATGGAGACGAGGGA", "CATGAAGAAATGGAGACGGGGGA", "ATTACACACTCGCTGGGTGGCGG",
            "ATTACACACTCTCTGGGTGGTGG", "ATTACGCACTCGCTGGGTGGCGG", "ATCACCCACTCCCTGGGTGGTGG", "ATCACCCACTCGCTCGGTGGTGG",
            "ATCACCCACTCCCTCGGCGGCGG", "CATGAAGAAGTGCAGACGGGGGA", "CATGAAAAAGTGCAGACGAGGGA", "ATTACACACTCGCTGGGTGGTGG",
            "ATCACCCACTCCCTTGGTGGTGG", "TCCCCCGTCTCCACTTCTTTATG"
)

TEF3_F <- c("CTTCATCTTCCAACCACCAGA", "CTTGAGGGTGTCAAGACCAAG", "CTTCATCTTCCAACCACCGGA", "CTCGAGGGTGTCAAGACCAAG",
            "CTGGAGGGTGTCAAGACCAAG", "CTTGAGGGCGTCAAGACCAAG", "CTTGGTCTTGACACCTTCGAG", "CTTGGTTTTGACACCCTCAAG",
            "CTTGGTCTTGACACCTTCAAG"
)

TEF3_R <- c("TCTGGTGGTTGGAAGATGAAG", "CTTGGTCTTGACACCCTCAAG", "TCCGGTGGTTGGAAGATGAAG", "CTTGGTCTTGACACCCTCGAG"
)

PGK_F <- c("ATCTTGTCAGAGACCTTGGCGCCGC", "GTCGGTGCCATTCCCACCATCAAGC", "GTCGGCGCCATCCCGACCATCAAGC", "GTTGGCGCCATCCCCACCATCAAGC",
           "ATCTTGTCAGAGACCTTGGCACCGC", "GTCGGTGCCATCCCTACCATCAAGC", "ATCTTGTCAGAGACCTTGGCACCAC", "ATCTTGTCAGAGACCTTAGCACCGC",
           "GTCGGCGCCATCCCCACCATCAAGC", "GTCGGCGCCATCCCTACCATCAAGC", "GTCGGTGCCATCCCCACCATCAAGC", "GTTGGCGCCATCCCTACCATCAAGC",
           "GCCGGTGCCATCCCCACCATCAAGC", "GTCGGTGCTATCCCTACCATCAAGC", "ATCTTGTCAGAGACCTTGGCACCTC", "ATCTTGTCAGAGACCTTGGCGCCAC",
           "GCTTGATGGTCGGAATGGCACCGAC", "ATTTGATGGTTGGGATAGCGCCAAC", "GCGGCGCCAAGGTCTCCGACAAGAT", "GCGGGGCCAAGGTCTCTGACAAGAT",
           "GTGGTGCCAAGATCTCTGACAAGAT", "GCTTGATGGTAGGAATGGCGCCGAC"
)

PGK_R <- c("GCGGCGCCAAGGTCTCTGACAAGAT", "GCTTGATGGTGGGAATGGCACCGAC", "GCTTGATGGTCGGGATGGCGCCGAC", "GCTTGATGGTAGGGATGGCGCCAAC",
           "GCGGTGCCAAGGTCTCTGACAAGAT", "GCTTGATGGTAGGGATGGCACCGAC", "GTGGTGCCAAGGTCTCTGACAAGAT", "GTGGTGCTAAGGTCTCTGACAAGAT",
           "GCTTGATGGTGGGGATGGCACCGAC", "GCTTGATGGTAGGGATGGCGCCGAC", "GCTTGATGGTGGGGATGGCGCCGAC", "GCTTGATGGTAGGGACGGCACCGAC",
           "GCTTGATGGTGGGGATGGCACCGGC", "GCTTGATGGTAGGAATAGCACCGAC", "GAGGTGCCAAGGTCTCTGACAAGAT", "GTGGCGCCAAGGTCTCTGACAAGAT",
           "GTCGCCATTCCGTCGACCATCAAGC", "GTTGGCGCTATCCCAACCATCAAAT", "ATCTTGTCGGAGACCTTGGTCGTCG", "ATCTTGTCAGAGACCTTCCCCGTCG",
           "ATCTTGTCAGAGATCTTGGTCGTCG", "GTCGGTATTCCTATCGACCATCAAGC"
)