TEF1 <- c("CATCGAGAAGTTCGAGAAGG","AACTTGCAGGCAATGTGG")

RPB2 <- c(  "GATGATAGAGATCACTTTGG","GATGATAGAGATCACTTCGG","GATGATAGAGATCACTATGG","GATGATAGAGATCACTATCG",
                          "GATGATAGTGATCACTTTGG","GATGATAGTGATCACTTCGG","GATGATAGTGATCACTATGG","GATGATAGTGATCACTATCG",
                          "GATGATCGAGATCACTTTGG","GATGATCGAGATCACTTCGG","GATGATCGAGATCACTATGG","GATGATCGAGATCACTATCG",
                          "GATGATCGTGATCACTTTGG","GATGATCGTGATCACTTCGG","GATGATCGTGATCACTATGG","GATGATCGTGATCACTATCG",
                          "GATGACAGAGATCACTTTGG","GATGACAGAGATCACTTCGG","GATGACAGAGATCACTATGG","GATGACAGAGATCACTATCG",
                          "GATGACAGTGATCACTTTGG","GATGACAGTGATCACTTCGG","GATGACAGTGATCACTATGG","GATGACAGTGATCACTATCG",
                          "GATGACCGAGATCACTTTGG","GATGACCGAGATCACTTCGG","GATGACCGAGATCACTATGG","GATGACCGAGATCACTATCG",
                          "GATGACCGTGATCACTTTGG","GATGACCGTGATCACTTCGG","GATGACCGTGATCACTATGG","GATGACCGTGATCACTATCG",
                          "GACGATAGAGATCACTTTGG","GACGATAGAGATCACTTCGG","GACGATAGAGATCACTATGG","GACGATAGAGATCACTATCG",
                          "GACGATAGTGATCACTTTGG","GACGATAGTGATCACTTCGG","GACGATAGTGATCACTATGG","GACGATAGTGATCACTATCG",
                          "GACGATCGAGATCACTTTGG","GACGATCGAGATCACTTCGG","GACGATCGAGATCACTATGG","GACGATCGAGATCACTATCG",
                          "GACGATCGTGATCACTTTGG","GACGATCGTGATCACTTCGG","GACGATCGTGATCACTATGG","GACGATCGTGATCACTATCG",
                          "GACGACAGAGATCACTTTGG","GACGACAGAGATCACTTCGG","GACGACAGAGATCACTATGG","GACGACAGAGATCACTATCG",
                          "GACGACAGTGATCACTTTGG","GACGACAGTGATCACTTCGG","GACGACAGTGATCACTATGG","GACGACAGTGATCACTATCG",
                          "GACGACCGAGATCACTTTGG","GACGACCGAGATCACTTCGG","GACGACCGAGATCACTATGG","GACGACCGAGATCACTATCG",
                          "GACGACCGTGATCACTTTGG","GACGACCGTGATCACTTCGG","GACGACCGTGATCACTATGG","GACGACCGTGATCACTATCG",
                          "CCCATAGCTTGTTTACCCAT","CCCATAGCTTGTTTGCCCAT","CCCATAGCTTGCTTACCCAT","CCCATAGCTTGCTTGCCCAT",
                          "CCCATGGCTTGTTTACCCAT","CCCATGGCTTGTTTGCCCAT","CCCATGGCTTGCTTACCCAT","CCCATGGCTTGCTTGCCCAT",
                          "ATGGGTAAACAAGCCATGGG","GACGATCGCGACCACTTTGG"
)
ITS <-  c("GGAAGTAAAAGTCGTAACAAGG","TCCTCCGCTTATTGATATGC")

LNS2 <- c(
  "GTCCAGTCTCGGCCAATCATGTTGAGCACATGGCC",
  "GACGGCGGTCCTTTCTATGCCGGGTTTGGCAACCG",
  "AACGGCGGTCCTTTCTATGCCGGCTTTGGCAACCG",
  "GTCCAGTCTCGGCCAATCATGTTGAGCACATGACC",
  "GTCCAGTCTCGACCAATCATGTTTAGCACATGACC",
  "GACGGTGGTCCTTTCTATGCCGGGTTTGGCAACCG",
  "GACGGCGGACCTTTCTATGCCGGTTTTGGCAACCG",
  "GTCCAGTCTCGGCCAATCATATTCAGCACATGACC",
  "GTCCAGTCTCGGCCGATCATGTTGAGCACATGGCC",
  "GACGGCGGTCCTTTCTATGCCGGTTTCGGCAATCG",
  "GACACCGTCCCCTTCTATGCCGGTTTTGGCAACCG",
  "GTCCAGTCTCGGCCAATCATGTTCAGCACATGGCC",
  "GTCCAGTCGCGGCCAATCATGTTGAGCACATGGCC",
  "GTCCAGTCTCGGCCAATCATGTTCAACACATGGCC",
  "GTCCAGTCTCGGCCAATCATATTCAGCACATGCCC",
  "GACGGCGGTCCTTTCTATGCCGGATTTGGCAACCG",
  "GTCCAGTCTCGGCCAATCATATTCAGCACATGGCC",
  "GACGGTACTCCTTTCTATGCCGGTTTTGGCAACCG",
  "GACGGTGGTCCTTTCTATGCCGGTTTTGGCAACCG",
  "GATGGCGGCCCTTTCTATGCTGGATTCGGCAACCG",
  "GACGGCGGTCCCTTCTATGCCGGGTTCGGCAACCG",
  "GTCCAGTCTCGGCCAATCATGTTGAGTACATGACC",
  "GACGGTGGTCCTTTCTATGCCGGATTTGGCAACCG",
  "GACGGTGGTCCTTTCTATGCCGGCTTTGGCAACCG",
  "GACGGTGGTCCTTTCTACGCCGGGTTTGGCAACCG",
  "GACGGCGGTCCCTTCTACGCCGGGTTTGGCAACCG",
  "CGGTTGCCAAAGCCGGCGTAGAATGGACCGCCGTT",
  "GGTCATGTGCTCAACATGATTGGCCGAGACTGGAC",
  "GGCCATGTGCTCAACATGATTGGCCGCGACTGGAC",
  "CGGTTGCCAAACCCGGCATAGAAAGGACCGCCGTC",
  "CGGTTGCCAAAGCCGGCATAGAATGGACCTCCGTC",
  "GGCCATGTGCTCAACATGATTGGCCGAGACTGGAC",
  "CGGTTACCAAAACCGGCGTAGAAAGGACCGCCGTC",
  "CGGTTGCCAAAGCCGGCGTAGAAAGGACCGCCGTT",
  "GGCCATGTGCTCAACATGATCGGCCGAGACTGGAC",
  "GGCCACGTGCTCAACATGATCGGCCGAGACTGGAC",
  "CGGTTGCCAAAGCCGGCATAGAATGGACCACCGTC",
  "CGGTTGCCAAAGCCGGCATAGAAAGGACCGCCGTT",
  "CGGTTGCCAAATCCGGCATAGAAAGGAGTACCGTC",
  "CGGTTGCCAAAACCGGCATAGAAAGGACCACCGTC",
  "CGGTTGCCAAAGCCGGCATAGAAAGGACCACCGTC",
  "GGTCATGTGCTGAACATGATTGGTCGAGACTGGAC",
  "GGCCATGTGCTGAACATGATCGGTCGAGACTGGAC",
  "GGCCATGTGCTGAATATGATTGGCCGAGACTGGAC",
  "GGTCATGTGCTCAACTATATTGGCCGAGACTGGAC",
  "CGGTTGCCAAAGCCGGCATAGAAAGGACCGCCATC",
  "CGGTTGCCGAAACCGGCATAGAAAGGACCACCGTC",
  "CGGTTGCCAAAACCGGCATAGAAAGGAGTGCCGTC",
  "GGCCATGTGCTGAACATGATTGGCCGAGATTGGAC",
  "CGGTTACCAAACCCGGCATAGAAAGGACCGCCGTC",
  "CGGTTGCCAAACCCGGCGTAGAATGGACCGCCGTT",
  "CGGTTGCCAAAACCGGCATAGAAAGGAGTACCGTC",
  "CGGTTGCCAAAGCCGGCATAGAAAGGACCGCCGTC",
  "CGGTTGCCAAACCCGGCATAGAAAGGACCGCCGTT",
  "GGCCATGTGCTGAACATGATTGGCCGAGACTGGAC"
)

ACT <- c(
  "TGGGTCAGAAGGACTCCTA",
  "CGAAACCGGCCTTGCACAT",
  "TGGGCCAGAAGGACTCTTA",
  "TGGGCCAGAAGGACTCCTA",
  "CGAAACCGGCTTTGCACAT",
  "TGGGTCAGAAGGACTCTTA",
  "ATGTGCAAGGCCGGTTTCG",
  "TAGGAGTCCTTCTGACCCA",
  "ATGTGCAAGGCCGGTTTTG",
  "TAGGAGTCCTTCTGGCCCA",
  "TAAGAGTCCTTCTGGCCCA"
)

TUB2 <- c(
  "CCACCGCCGAGGGAGTGGGTGAT",
  "CCACCACCCAGCGAGTGCGTAAT",
  "TCCCTCGTCTGCACTTCTTCATG",
  "TCCCTCGCCTGCACTTCTTCATG",
  "CCACCACCGAGGGAGTGGGTGAT",
  "TCCCTCGTCTCCACTTCTTCATG",
  "CCACCACCCAGGGAGTGTGTAAT",
  "TTCCTCGTCTGCACTTCTTCATG",
  "TCCCCCGTCTCCACTTCTTCATG",
  "CCACCGCCAAGGGAGTGTGTAAT",
  "CCACCACCAAGGGAGTGGGTGAT",
  "TCCCTCGTCTTCACTTCTTCATG",
  "CCACCACCCAGGGAGTGCGTAAT",
  "TCCCGCGTCTCCACTTCTTTATG",
  "CCACCACCCAGGGAGTGGGTAAT",
  "TCCCTCGTCTGCATTTCTTCATG",
  "CCACCACCGAGAGAGTGGGTGAT",
  "TCCCTCGTCTCCATTTCTTCATG",
  "TCCCCCGTCTCCATTTCTTCATG",
  "CCGCCACCCAGCGAGTGTGTAAT",
  "CCACCACCCAGAGAGTGTGTAAT",
  "CCGCCACCCAGCGAGTGCGTAAT",
  "CCACCACCCAGGGAGTGGGTGAT",
  "CCACCACCGAGCGAGTGGGTGAT",
  "CCGCCACCGAGGGAGTGGGTGAT",
  "TCCCCCGTCTGCACTTCTTCATG",
  "TCCCTCGTCTGCACTTTTTCATG",
  "CCACCACCCAGCGAGTGTGTAAT",
  "CCACCGCCAAGGGAGTGGGTGAT",
  "CATAAAGAAGTGGAGACGGGGGA",
  "CATGAAGAAGTGCAGACGAGGGA",
  "CATGAAGAAGTGGAGACGGGGGA",
  "ATTACACACTCCCTGGGTGGTGG",
  "ATTACCCACTCGCTGGGTGGTGG",
  "CATGAAGAAGTGAAGACGAGGGA",
  "CATGAAGAAATGGAGACGGGGGA",
  "ATTACCCACTCCCTGGGTGGTGG",
  "ATCACCCACTCCCTCGGTGGTGG",
  "ATCACACACTCCCTTGGTGGTGG",
  "CATGAAGAAATGCAGACGAGGGA",
  "ATTACACACTCCTTGGGTGGTGG",
  "ATTACTCACTCTCTTGGTGGTGG",
  "ATCACCCACTCCCTGGGTGGTGG",
  "CATGAAGAAGTGGAGACGAGGGA",
  "ATTACCCACTCGCTGGGTGGCGG",
  "ATCACCCACTCCCTCGGCGGTGG",
  "ATCACCCACTCTCTCGGTGGTGG",
  "ATCACCCACTCCCTTGGTGGTGG",
  "ATCACGCACTCCCTGGGTGGTGG",
  "CATGAAGAAGTGTAGACGAGGGA",
  "ATCACTCACTCCCTGGGTGGTGG",
  "ATCACCCACTCCCTCGGTGGCGG",
  "ATTACACACTCCCTGGGCGGTGG",
  "CATAAAGAAGTGCAGACGAGGGA",
  "CATGAAAAAGTGCAGACGAGGGA",
  "ATCACCCACTCCCTCGGCGGCGG",
  "ATTACGCACTCGCTGGGTGGTGG",
  "ATCACCCACTCGCTCGGTGGTGG",
  "ATTACGCACTCCCTGGGTGGTGG"
)

TEF3 <- c(
  "CTTCATCTTCCAACCACCAGA",
  "CTTGAGGGTGTCAAGACCAAG",
  "CTTCATCTTCCAACCACCGGA",
  "CTCGAGGGTGTCAAGACCAAG",
  "CTGGAGGGTGTCAAGACCAAG",
  "CTTGAGGGCGTCAAGACCAAG",
  "CTTGGTCTTGACACCCTCGAG",
  "TCCGGTGGTTGGAAGATGAAG",
  "TCTGGTGGTTGGAAGATGAAG",
  "CTTGGTCTTGACACCCTCAAG",
  "CTTGGTCTTGACACCTTCGAG",
  "CTTGGTTTTGACACCCTCAAG",
  "CTTGGTCTTGACACCTTCAAG"
)

PGK <- c(
  "ATCTTGTCAGAGACCTTGGCGCCGC",
  "GTCGGTGCCATTCCCACCATCAAGC",
  "GTCGGCGCCATCCCGACCATCAAGC",
  "GTTGGCGCCATCCCCACCATCAAGC",
  "ATCTTGTCAGAGACCTTGGCACCGC",
  "GTCGGTGCCATCCCTACCATCAAGC",
  "ATCTTGTCAGAGACCTTGGCACCAC",
  "ATCTTGTCAGAGACCTTGGCACCTC",
  "ATCTTGTCAGAGACCTTAGCACCGC",
  "GTCGGCGCCATCCCCACCATCAAGC",
  "ATCTTGTCAGAGACCTTGGCGCCAC",
  "GTCGGCGCCATCCCTACCATCAAGC",
  "GTCGGTGCCATCCCCACCATCAAGC",
  "GTTGGCGCCATCCCTACCATCAAGC",
  "GCCGGTGCCATCCCCACCATCAAGC",
  "GTCGGTGCTATCCCTACCATCAAGC",
  "GCTTGATGGTCGGGATGGCGCCGAC",
  "GCGGCGCCAAGGTCTCTGACAAGAT",
  "GTGGTGCCAAGGTCTCTGACAAGAT",
  "GCTTGATGGTGGGAATGGCACCGAC",
  "GCTTGATGGTGGGGATGGCACCGAC",
  "ATTTGATGGTTGGGATAGCGCCAAC",
  "GCGGTGCCAAGGTCTCTGACAAGAT",
  "GCGGCGCCAAGGTCTCCGACAAGAT",
  "GCTTGATGGTAGGGATGGCGCCAAC",
  "GCTTGATGGTGGGGACGGCACCGAC",
  "GTGGTGCTAAGGTCTCTGACAAGAT",
  "GCTTGATGGTAGGGATGGCGCCGAC",
  "GCTTGATGGTAGGAATAGCACCGAC",
  "GCGGGGCCAAGGTCTCTGACAAGAT",
  "GTGGTGCCAAGATCTCTGACAAGAT",
  "GCTTGATGGTAGGGACGGCACCGAC",
  "GCTTGATGGTGGGGATGGCGCCGAC",
  "GCTTGATGGTAGGGATGGCACCGAC",
  "GCTTGATGGTGGGGATGGCACCGGC",
  "GCTTGATGGTGGGAATGGCGCCGAC"
)

ACL1 <- c("AGCCCGATCAGCTCATCAAG","AGCCTGATCAGCTCATCAAG","CTTGATGAGCTGATCGGGCT","CTTAATGAGCTGATCGGGCT","TTTGATGAGCTGATCGGGCT",
          "CCTGGCAGCAAGATCAAGGAAGT","CCTGGCAGCAAGATCCAGGAAGT","CCTGGCAGCAAGATCGAGGAAGT","CTTGGCAGCAAGATCCAGGAAGT","CTTGGCAGCAAGATCTAGGAAGT",
          "CTTGGCGGCAAGATCCAGGAAGT","CTTGGCCGCAAGATCCAGGAAGT","CTTAGCAGCAAGATCCAGGAAGT","ACTTCCTGGATCTTGCTGCCAAG","ACTTCTTAGATCTTGCTGCCAAG")

TEF1_F <- c("CATCGAGAAGTTCGAGAAGG")

TEF1_R <- c("AACTTGCAGGCAATGTGG")

ITS_F <- c("GGAAGTAAAAGTCGTAACAAGG")

ITS_R <- c("TCCTCCGCTTATTGATATGC")

RPB2_F <- c("GATGATAGAGATCACTTTGG","GATGATAGAGATCACTTCGG","GATGATAGAGATCACTATGG","GATGATAGAGATCACTATCG",
            "GATGATAGTGATCACTTTGG","GATGATAGTGATCACTTCGG","GATGATAGTGATCACTATGG","GATGATAGTGATCACTATCG",
            "GATGATCGAGATCACTTTGG","GATGATCGAGATCACTTCGG","GATGATCGAGATCACTATGG","GATGATCGAGATCACTATCG",
            "GATGATCGTGATCACTTTGG","GATGATCGTGATCACTTCGG","GATGATCGTGATCACTATGG","GATGATCGTGATCACTATCG",
            "GATGACAGAGATCACTTTGG","GATGACAGAGATCACTTCGG","GATGACAGAGATCACTATGG","GATGACAGAGATCACTATCG",
            "GATGACAGTGATCACTTTGG","GATGACAGTGATCACTTCGG","GATGACAGTGATCACTATGG","GATGACAGTGATCACTATCG",
            "GATGACCGAGATCACTTTGG","GATGACCGAGATCACTTCGG","GATGACCGAGATCACTATGG","GATGACCGAGATCACTATCG",
            "GATGACCGTGATCACTTTGG","GATGACCGTGATCACTTCGG","GATGACCGTGATCACTATGG","GATGACCGTGATCACTATCG",
            "GACGATAGAGATCACTTTGG","GACGATAGAGATCACTTCGG","GACGATAGAGATCACTATGG","GACGATAGAGATCACTATCG",
            "GACGATAGTGATCACTTTGG","GACGATAGTGATCACTTCGG","GACGATAGTGATCACTATGG","GACGATAGTGATCACTATCG",
            "GACGATCGAGATCACTTTGG","GACGATCGAGATCACTTCGG","GACGATCGAGATCACTATGG","GACGATCGAGATCACTATCG",
            "GACGATCGTGATCACTTTGG","GACGATCGTGATCACTTCGG","GACGATCGTGATCACTATGG","GACGATCGTGATCACTATCG",
            "GACGACAGAGATCACTTTGG","GACGACAGAGATCACTTCGG","GACGACAGAGATCACTATGG","GACGACAGAGATCACTATCG",
            "GACGACAGTGATCACTTTGG","GACGACAGTGATCACTTCGG","GACGACAGTGATCACTATGG","GACGACAGTGATCACTATCG",
            "GACGACCGAGATCACTTTGG","GACGACCGAGATCACTTCGG","GACGACCGAGATCACTATGG","GACGACCGAGATCACTATCG",
            "GACGACCGTGATCACTTTGG","GACGACCGTGATCACTTCGG","GACGACCGTGATCACTATGG","GACGACCGTGATCACTATCG",
            "GACGATCGCGACCACTTTGG"
)

RPB2_R <- c("CCCATAGCTTGTTTACCCAT","CCCATAGCTTGTTTGCCCAT","CCCATAGCTTGCTTACCCAT","CCCATAGCTTGCTTGCCCAT",
            "CCCATGGCTTGTTTACCCAT","CCCATGGCTTGTTTGCCCAT","CCCATGGCTTGCTTACCCAT","CCCATGGCTTGCTTGCCCAT",
            "ATGGGTAAACAAGCCATGGG"
)

LNS2_F <- c(
  "GTCCAGTCTCGGCCAATCATGTTGAGCACATGGCC", "GTCCAGTCTCGGCCAATCATGTTGAGCACATGACC", 
  "GTCCAGTCTCGACCAATCATGTTTAGCACATGACC", "GTCCAGTCTCGGCCAATCATATTCAGCACATGACC", 
  "GTCCAGTCTCGGCCGATCATGTTGAGCACATGGCC", "GTCCAGTCTCGGCCAATCATGTTCAGCACATGGCC", 
  "GTCCAGTCGCGGCCAATCATGTTGAGCACATGGCC", "GTCCAGTCTCGGCCAATCATGTTCAACACATGGCC", 
  "GTCCAGTCTCGGCCAATCATATTCAGCACATGCCC", "GTCCAGTCTCGGCCAATCATATTCAGCACATGGCC", 
  "GTCCAGTCTCGGCCAATCATGTTGAGTACATGACC", "GGCCATGTGCTCAACATGATTGGCCGAGACTGGAC", 
  "GGTCATGTGCTCAACATGATTGGCCGAGACTGGAC", "GGTCATGTGCTAAACATGATTGGTGGAGACTGGAC", 
  "GGTCATGTGCTGAATATGATTGGCCGAGACTGGAC", "GGCCATGTGCTCAACATGATCGGCCGAGACTGGAC", 
  "GGCCATGTGCTGAACATGATTGGCCGAGACTGGAC", "GGCCATGTGCTCAACATGATTGGCGCGACTGGAC", 
  "GGCCATGTGTTGAACATGATTGGCCGAGACTGGAC", "GGGCATGTGCTGAATATGATTGGCCGAGACTGGAC", 
  "GGCCATGTGCTGAATATGATTGGCCGAGACTGGAC", "GGTCATGTACTCAACATGATTGGCCGAGACTGGAC"
)

LNS2_R <- c(
  "GACGGCGGTCCTTTCTATGCCGGGTTTGGCAACCG", "AACGGCGGTCCTTTCTATGCCGGCTTTGGCAACCG", 
  "GACGGTGGTCCTTTCTATGCCGGGTTTGGCAACCG", "GACGGCGGACCTTTCTATGCCGGTTTTGGCAACCG", 
  "GACGGCGGTCCTTTCTATGCCGGTTTCGGCAATCG", "GACACCGTCCCCTTCTATGCCGGTTTTGGCAACCG", 
  "GACGGCGGTCCTTTCTATGCCGGATTTGGCAACCG", "GACGGTACTCCTTTCTATGCCGGTTTTGGCAACCG", 
  "GACGGTGGTCCTTTCTATGCCGGTTTTGGCAACCG", "GATGGCGGCCCTTTCTATGCTGGATTCGGCAACCG", 
  "GACGGCGGTCCCTTCTATGCCGGGTTCGGCAACCG", "GACGGTGGTCCTTTCTATGCCGGATTTGGCAACCG", 
  "GACGGTGGTCCTTTCTATGCCGGCTTTGGCAACCG", "GACGGTGGTCCTTTCTACGCCGGGTTTGGCAACCG", 
  "GACGGCGGTCCCTTCTACGCCGGGTTTGGCAACCG", "GACGGCGGTCCTTTCTATGCCGGTTTTGGCAACCG", 
  "GACGGTGGTCCTTTCTATGCCGGCTTTGGCAACCG", "CGGTTGCCAAACCCGGCATAGAAAGGACCGCCGTC", 
  "CGGTTGCCAAAGCCGGCATAGAATGGACCGCCGTT", "CGGTTGCCAAACCCGGCATAGAAAGGACCACCGTC", 
  "CGGTTGCCAAAACCGGCATAGAAAGGTCCGCCGTC", "CGATTGCCGAAACCGGCATAGAAAGGACCGCCGTC", 
  "CGGTTGCCAAAACCGGCATAGAAGGGGACGGTGTC", "CGGTTGCCAAATCCGGCATAGAAAGGACCGCCGTC", 
  "CGGTTGCCAAAACCGGCATAGAAAGGAGTACCGTC", "CGGTTGCCAAAACCGGCATAGAAAGGACCACCGTC", 
  "CGGTTGCCGAATCCAGCATAGAAAGGCCGCCATC", "CGGTTGCCGAACCCGGCATAGAAAGGACCGCCGTC", 
  "CGGTTGCCAAATCCGGCATAGAAAGGACCACCGTC", "CGGTTGCCAAAGCCGGCATAGAAAGGACCACCGTC", 
  "CGGTTGCCAAACCCGGCGTAGAAAGGACCACCGTC", "CGGTTGCCGAACCCGGCGTAGAAGGACCGCCGTC", 
  "CGGTTGCCAAAACCGGCATAGAAAGGACCGCCGTC", "CGGTTGCCAAAGCCGGCATAGAAAGGACCACCGTC"
)

ACT_F <- c(
  "TGGGTCAGAAGGACTCCTA", "TGGGCCAGAAGGACTCTTA", "TGGGCCAGAAGGACTCCTA", 
  "TGGGTCAGAAGGACTCTTA", "TAGGAGTCCTTCTGACCCA", "TAAGAGTCCTTCTGGCCCA", 
  "TAGGAGTCCTTCTGGCCCA"
)

ACT_R <- c(
  "CGAAACCGGCCTTGCACAT", "CGAAACCGGCTTTGCACAT", "ATGTGCAAGGCCGGTTTTG", 
  "ATGTGCAAGGCCGGTTTCG"
)

TUB2_F <- c(
  "CCACCGCCGAGGGAGTGGGTGAT", "CCACCACCCAGCGAGTGCGTAAT", "CCACCACCGAGGGAGTGGGTGAT", 
  "CCACCACCCAGGGAGTGTGTAAT", "CCACCGCCAAGGGAGTGTGTAAT", "CCACCACCAAGGGAGTGGGTGAT", 
  "CCACCACCCAGGGAGTGCGTAAT", "CCACCACCCAGGGAGTGGGTAAT", "CCACCACCGAGAGAGTGGGTGAT", 
  "CCGCCACCCAGCGAGTGTGTAAT", "CCACCACCCAGAGAGTGTGTAAT", "CCGCCACCCAGCGAGTGCGTAAT", 
  "CCACCACCCAGGGAGTGGGTGAT", "CCACCACCGAGCGAGTGGGTGAT", "CCGCCACCGAGGGAGTGGGTGAT", 
  "CCACCACCCAGCGAGTGTGTAAT", "CCACCGCCAAGGGAGTGGGTGAT", "ATCACCCACTCCCTCGGCGGTGG", 
  "ATTACGCACTCGCTGGGTGGTGG", "ATCACCCACTCCCTCGGTGGTGG", "ATTACACACTCCCTGGGTGGTGG", 
  "ATTACACACTCCTTGGGTGGTGG", "ATCACCCACTCCTTGGTGGTGG", "ATTACGCACTCCCTGGGTGGTGG", 
  "ATTACCCACTCCCTGGGTGGTGG", "ATCACCCACTCTCTCGGTGGTGG", "ATTACACACTCGCTGGGTGGCGG", 
  "ATTACACACTCTCTGGGTGGTGG", "ATTACGCACTCGCTGGGTGGCGG", "ATCACCCACTCCCTGGGTGGTGG", 
  "ATCACCCACTCGCTCGGTGGTGG", "ATCACCCACTCCCTCGGCGGCGG", "ATTACACACTCGCTGGGTGGTGG", 
  "ATCACCCACTCCCTTGGTGGTGG"
)

TUB2_R <- c(
  "TCCCTCGTCTGCACTTCTTCATG", "TCCCTCGCCTGCACTTCTTCATG", "TCCCTCGTCTCCACTTCTTCATG", 
  "TTCCTCGTCTGCACTTCTTCATG", "TCCCCCGTCTCCACTTCTTCATG", "TCCCTCGTCTTCACTTCTTCATG", 
  "TCCCGCGTCTCCACTTCTTTATG", "TCCCTCGTCTGCATTTCTTCATG", "TCCCTCGTCTCCATTTCTTCATG", 
  "TCCCCCGTCTCCATTTCTTCATG", "TCCCCCGTCTGCACTTCTTCATG", "TCCCTCGTCTGCACTTTTTCATG", 
  "CATAAAGAAGTGGAGACGGGGGA", "CATGAAGAAGTGCAGACGAGGGA", "CATGAAGAAGTGCAGGCGAGGGA", 
  "CATGAAGAAGTGGAGACGAGGGA", "CATGAAGAAGTGCAGACGAAGAA", "CATGAAGAAATGGAGACGGGGGA", 
  "CATGAAGAAGTGAAGACGAGGGA", "CATAAAGAAGTGGAGACGCGGGA", "CATGAAGAAATGCAGACGAGGGA", 
  "CATGAAGAAATGGAGACGAGGGA", "CATGAAGAAATGGAGACGGGGGA", "CATGAAGAAGTGCAGACGGGGGA", 
  "CATGAAAAAGTGCAGACGAGGGA", "TCCCCCGTCTCCACTTCTTTATG"
)

TEF3_F <- c(
  "TCTGGTGGTTGGAAGATGAAG", "TCCGGTGGTTGGAAGATGAAG",
  "CTTCATCTTCCAACCACCAGA", "CTTCATCTTCCAACCACCGGA"
)

TEF3_R <- c(
  "CTTGGTCTTGACACCCTCAAG", "CTTGGTCTTGACACCCTCGAG",
  "CTTGGTCTTGACACCTTCGAG", "CTTGGTTTTGACACCCTCAAG", 
  "CTTGGTCTTGACACCTTCAAG",  "CTTGAGGGTGTCAAGACCAAG", 
  "CTCGAGGGTGTCAAGACCAAG",  "CTGGAGGGTGTCAAGACCAAG", 
  "CTTGAGGGCGTCAAGACCAAG"
)

PGK_F <- c(
  "ATCTTGTCAGAGACCTTGGCGCCGC", "ATCTTGTCAGAGACCTTGGCACCGC", 
  "ATCTTGTCAGAGACCTTGGCACCAC", "ATCTTGTCAGAGACCTTAGCACCGC", 
  "ATCTTGTCAGAGACCTTGGCACCTC", "ATCTTGTCAGAGACCTTGGCGCCAC", 
  "GCGGCGCCAAGGTCTCCGACAAGAT", "GCGGGGCCAAGGTCTCTGACAAGAT", 
  "GTGGTGCCAAGATCTCTGACAAGAT", "GCGGCGCCAAGGTCTCTGACAAGAT", 
  "GCGGTGCCAAGGTCTCTGACAAGAT", "GTGGTGCCAAGGTCTCTGACAAGAT", 
  "GTGGTGCTAAGGTCTCTGACAAGAT", "GAGGTGCCAAGGTCTCTGACAAGAT", 
  "GTGGCGCCAAGGTCTCTGACAAGAT", "ATCTTGTCGGAGACCTTGGTCGTCG", 
  "ATCTTGTCAGAGACCTTCCCCGTCG", "ATCTTGTCAGAGATCTTGGTCGTCG"
)

PGK_R <- c(
  "GTCGGTGCCATTCCCACCATCAAGC", "GTCGGCGCCATCCCGACCATCAAGC", 
  "GTTGGCGCCATCCCCACCATCAAGC", "GTCGGTGCCATCCCTACCATCAAGC", 
  "GTCGGCGCCATCCCCACCATCAAGC", "GTCGGCGCCATCCCTACCATCAAGC", 
  "GTCGGTGCCATCCCCACCATCAAGC", "GTTGGCGCCATCCCTACCATCAAGC", 
  "GCCGGTGCCATCCCCACCATCAAGC", "GTCGGTGCTATCCCTACCATCAAGC", 
  "GCTTGATGGTCGGAATGGCACCGAC", "ATTTGATGGTTGGGATAGCGCCAAC", 
  "GCTTGATGGTAGGAATGGCGCCGAC", "GCTTGATGGTGGGAATGGCACCGAC", 
  "GCTTGATGGTCGGGATGGCGCCGAC", "GCTTGATGGTAGGGATGGCGCCAAC", 
  "GCTTGATGGTAGGGATGGCACCGAC", "GCTTGATGGTGGGGATGGCACCGAC", 
  "GCTTGATGGTAGGGATGGCGCCGAC", "GCTTGATGGTGGGGATGGCGCCGAC", 
  "GCTTGATGGTAGGGACGGCACCGAC", "GCTTGATGGTGGGGATGGCACCGGC", 
  "GCTTGATGGTAGGAATAGCACCGAC", "GTCGCCATTCCGTCGACCATCAAGC", 
  "GTTGGCGCTATCCCAACCATCAAAT", "GTCGGTATTCCTATCGACCATCAAGC"
)

ACL1_F <- c("AGCCCGATCAGCTCATCAAG","AGCCTGATCAGCTCATCAAG","CTTGATGAGCTGATCGGGCT","CTTAATGAGCTGATCGGGCT","TTTGATGAGCTGATCGGGCT")

ACL1_R <- c("CCTGGCAGCAAGATCAAGGAAGT","CCTGGCAGCAAGATCCAGGAAGT","CCTGGCAGCAAGATCGAGGAAGT","CTTGGCAGCAAGATCCAGGAAGT","CTTGGCAGCAAGATCTAGGAAGT",
          "CTTGGCGGCAAGATCCAGGAAGT","CTTGGCCGCAAGATCCAGGAAGT","CTTAGCAGCAAGATCCAGGAAGT","ACTTCCTGGATCTTGCTGCCAAG","ACTTCTTAGATCTTGCTGCCAAG")